//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CodeBase/BombLogic/BombInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BombInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BombInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BombInput"",
    ""maps"": [
        {
            ""name"": ""Bomb"",
            ""id"": ""76b2b05a-62ac-47dc-8b4d-0df625953104"",
            ""actions"": [
                {
                    ""name"": ""Explode"",
                    ""type"": ""Button"",
                    ""id"": ""86433f22-f962-4239-935f-422a4fa0e405"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a580f65b-830e-4bfa-84b1-8d63df8a6ee1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Explode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bomb
        m_Bomb = asset.FindActionMap("Bomb", throwIfNotFound: true);
        m_Bomb_Explode = m_Bomb.FindAction("Explode", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bomb
    private readonly InputActionMap m_Bomb;
    private List<IBombActions> m_BombActionsCallbackInterfaces = new List<IBombActions>();
    private readonly InputAction m_Bomb_Explode;
    public struct BombActions
    {
        private @BombInput m_Wrapper;
        public BombActions(@BombInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Explode => m_Wrapper.m_Bomb_Explode;
        public InputActionMap Get() { return m_Wrapper.m_Bomb; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BombActions set) { return set.Get(); }
        public void AddCallbacks(IBombActions instance)
        {
            if (instance == null || m_Wrapper.m_BombActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BombActionsCallbackInterfaces.Add(instance);
            @Explode.started += instance.OnExplode;
            @Explode.performed += instance.OnExplode;
            @Explode.canceled += instance.OnExplode;
        }

        private void UnregisterCallbacks(IBombActions instance)
        {
            @Explode.started -= instance.OnExplode;
            @Explode.performed -= instance.OnExplode;
            @Explode.canceled -= instance.OnExplode;
        }

        public void RemoveCallbacks(IBombActions instance)
        {
            if (m_Wrapper.m_BombActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBombActions instance)
        {
            foreach (var item in m_Wrapper.m_BombActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BombActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BombActions @Bomb => new BombActions(this);
    public interface IBombActions
    {
        void OnExplode(InputAction.CallbackContext context);
    }
}
